// <auto-generated />
using System;
using Cataloger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cataloger.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804065701_AddCollectionItemTimeConstraint")]
    partial class AddCollectionItemTimeConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cataloger.Api.Entities.Books.BookContributorEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("BookId", "PersonId", "Role");

                    b.HasIndex("PersonId");

                    b.ToTable("BookContributors");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.EditionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TotalVolumes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Editions");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.PersonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.PublisherEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.SeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.CollectionItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CollectionItemEntity", t =>
                        {
                            t.HasCheckConstraint("CK_CollectionItem_Rating", "\"Rating\" IS NULL OR (\"Rating\" >= 0 AND \"Rating\" <= 5)");

                            t.HasCheckConstraint("CK_CollectionItem_UpdatedAt_After_CreatedAt", "\"UpdatedAt\" IS NULL OR \"UpdatedAt\" >= \"CreatedAt\"");
                        });

                    b.HasDiscriminator<string>("Discriminator").HasValue("CollectionItemEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.BookEntity", b =>
                {
                    b.HasBaseType("Cataloger.Api.Entities.CollectionItemEntity");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Volume")
                        .HasColumnType("integer");

                    b.HasIndex("EditionId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_CollectionItem_Rating", "\"Rating\" IS NULL OR (\"Rating\" >= 0 AND \"Rating\" <= 5)");

                            t.HasCheckConstraint("CK_CollectionItem_UpdatedAt_After_CreatedAt", "\"UpdatedAt\" IS NULL OR \"UpdatedAt\" >= \"CreatedAt\"");
                        });

                    b.HasDiscriminator().HasValue("BookEntity");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.BookContributorEntity", b =>
                {
                    b.HasOne("Cataloger.Api.Entities.Books.BookEntity", "Book")
                        .WithMany("Contributors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cataloger.Api.Entities.Books.PersonEntity", "Person")
                        .WithMany("Books")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.EditionEntity", b =>
                {
                    b.HasOne("Cataloger.Api.Entities.Books.PublisherEntity", "Publisher")
                        .WithMany("Editions")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cataloger.Api.Entities.Books.SeriesEntity", "Series")
                        .WithMany("Editions")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.BookEntity", b =>
                {
                    b.HasOne("Cataloger.Api.Entities.Books.EditionEntity", "Edition")
                        .WithMany("Books")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Edition");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.EditionEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.PersonEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.PublisherEntity", b =>
                {
                    b.Navigation("Editions");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.SeriesEntity", b =>
                {
                    b.Navigation("Editions");
                });

            modelBuilder.Entity("Cataloger.Api.Entities.Books.BookEntity", b =>
                {
                    b.Navigation("Contributors");
                });
#pragma warning restore 612, 618
        }
    }
}
